import distutils.sysconfig
import os
env = Environment(SWIGFLAGS=['-python','-c++'],
		  CPPPATH=[distutils.sysconfig.get_python_inc()])
env["ENV"]["PKG_CONFIG_PATH"] = os.environ.get("PKG_CONFIG_PATH")

lib_files = Split("""
		  src/saliency.cpp
		  src/gethog.cpp
""")

bloblib_files = Split("""
		  ../blobs/BlobExtraction.cpp
		  ../blobs/Blob.cpp
		  ../blobs/BlobResult.cpp
""")

swig_files = Split("""
	        """)
env.ParseConfig('pkg-config --cflags --libs opencv')

debug = ARGUMENTS.get('debug',0)
if int (debug):
   env.Append(CCFLAGS = '-g')
else:
   env.Append(CCFLAGS = '-O3')

env.Append(CPPPATH = ['include','../blobs'])

env.Append(LIBS = ['cppunit','boost_program_options-mt'])

env.Library('saliency', lib_files)
env.Library('blobs', bloblib_files)
run_files = Split("""src/main.cpp
		      """)
train_files = Split("""src/train.cpp
		      """)

test_files = Split("""test/test.cpp
		      """)
 
		      
#env = Environment();
env.Append(LIBS = ['saliency','blobs'])
env.Append(LIBPATH = ['.'])
env.Program('bin/saliency', run_files)
env.Program('bin/train', train_files)
env.Program('bin/unittest', test_files);

